[preset]

title = "Animals"

[home]

slug = "home"
name = "Home"
title = "Günstige Katzen- und Hundenahrung sowie Zubehör und Spielzeug von Top-Marken"
description = "Stöbern Sie in unserem großen Sortiment von mehr als 100.000 Tierprodukten von Futter über Spielzeug bis hin zu edlen Accessoires."
metaDescription = "Stöbern Sie in unserem großen Sortiment von mehr als 100.000 Tierprodukten von Futter über Spielzeug bis hin zu Accessoires."