[0]

slug = "hunde"
name = "Hund & Zubehör"
title = "Günstig Hunde-Zubehör einkaufen von der Leine bis zum Futter"
description = "Unser umfangreiches und hochwertiges Hunde-Sortiment hat für jeden Hundehalter die passenden Produkte von zahlreichen Hundeleinen bis hin zu Körben und Futtermitteln."
metaDescription = "Unser umfangreiches und hochwertiges Hunde-Sortiment hat für jeden Hundehalter die passenden Produkte."

tags[] = "hund"
tags[] = "hunde"

tagsNot[] = "katze"
tagsNot[] = "katzen"
tagsNot[] = "kleintier"
tagsNot[] = "kleintiere"

[1]

slug = "katzen"
name = "Katze & Zubehör"
title = "Günstig Katzen-Zubehör einkaufen vom Kratzbaum bis zum Futter"
description = "Unser umfangreiches und hochwertiges Schuh-Sortiment hat für jeden Schuh-Typ das passende Design. Bei uns werden alle Größen glücklich."
metaDescription = "Unser umfangreiches und hochwertiges Schuh-Sortiment hat für jeden Schuh-Typ das passende Design. Bei uns werden alle Größen glücklich."

tags[] = "katze"
tags[] = "katzen"

tagsNot[] = "hund"
tagsNot[] = "hunde"
tagsNot[] = "kleintier"
tagsNot[] = "kleintiere"

[2]

slug = "kleintiere"
name = "Kleintiere & Zubehör"
title = "Günstig hochwertiges Kleintier-Zubehör einkaufen für Hamster, Mehrschweinchen & Weitere"
description = "Unser umfangreiches und hochwertiges Kleintier-Sortiment bietet jedem Kleintier hochwertige Markenprodukte."
metaDescription = "Unser umfangreiches und hochwertiges Kleintier-Sortiment bietet jedem Kleintier hochwertige Markenprodukte."

tags[] = "kleintier"
tags[] = "kleintiere"

tagsNot[] = "hund"
tagsNot[] = "hunde"
tagsNot[] = "katze"
tagsNot[] = "katzen"

[3]

slug = "aquarium-fische"
name = "Aquarium & Fische"
title = "Günstig hochwertiges Aquarium-Zubehör und Fischfutter einkaufen von bekannten Markenherstellern"
description = "Unser umfangreiches und hochwertiges Aquarium- und Fisch-Sortiment bietet jedem Aquaristen das passende Zubehör."
metaDescription = "Unser umfangreiches und hochwertiges Aquarium- und Fisch-Sortiment bietet jedem Aquaristen das passende Zubehör."

tags[] = "aquarium"
tags[] = "fische"

tagsNot[] = "hund"
tagsNot[] = "hunde"
tagsNot[] = "katze"
tagsNot[] = "katzen"
tagsNot[] = "kleintier"
tagsNot[] = "kleintiere"

[4]

slug = "tierspielzeug"
name = "Tierspielzeug"
title = "Günstig hochwertiges Tierspielzeug einkaufen für alle Vierbeiner von Top-Marken"
description = "Unser umfangreiches und hochwertiges Schuh-Sortiment hat für jeden Schuh-Typ das passende Design. Bei uns werden alle Größen glücklich."
metaDescription = "Unser umfangreiches und hochwertiges Schuh-Sortiment hat für jeden Schuh-Typ das passende Design. Bei uns werden alle Größen glücklich."

tags[] = "spielzeug"
tags[] = "spielzeuge"

tagsNot[] = "tasche"
tagsNot[] = "taschen"
tagsNot[] = "bekleidung"
tagsNot[] = "kleintier"
tagsNot[] = "kleintiere"