[preset]

title = "Hardware"

[home]

slug = "home"
name = "Home"
title = "Günstig Heimwerker-Zubehör einkaufen vom Werzeug bis zur Schraube von Top-Marken"
description = "Stöbern Sie in unserem großen Heimwerker-Sortiment von mehr als 100.000 Teilen von Werkzeugen über Farben bis hin zu Möbeln."
metaDescription = "Stöbern Sie in unserem großen Heimwerker-Sortiment von mehr als 100.000 Teilen von Werkzeugen über Farben bis hin zu Möbeln."