[0]

slug = "werkzeuge-maschinen"
name = "Werkzeuge & Maschinen"
title = "Günstig Werkzeug und Maschinen einkaufen von der Bohrmaschine bis zur Gartengerät"
description = "Unser umfangreiches und hochwertiges Werkzeug- und Maschinen-Sortiment bietet jedem Handwerker das passende Arbeitsmittel."
metaDescription = "Unser umfangreiches und hochwertiges Werkzeug- und Maschinen-Sortiment bietet jedem Handwerker das passende Arbeitsmittel."

tags[] = "werkzeug"
tags[] = "maschine"

tagsNot[] = "reinigung"

[1]

slug = "garten-pflanzen"
name = "Garten & Pflanzen"
title = "Günstig Gartenzubehör und Pflanzen einkaufen von den Grassamen bis hin zum Blumentopf"
description = "Unser umfangreiches und hochwertiges Garten und Pflanzen-Sortiment bietet jedem Gärtner hochwertige Produkte."
metaDescription = "Unser umfangreiches und hochwertiges Garten und Pflanzen-Sortiment bietet jedem Gärtner hochwertige Produkte."

tags[] = "garten"
tags[] = "pflanzen"
tags[] = "gardena"

tagsNot[] = "bad"

[2]

slug = "haushalt-wohnen"
name = "Haushalt & Wohnen"
title = "Günstig Haushaltsprodukte und Wohnungseinrichtung einkaufen vom Esstisch bis zum Vorhang"
description = "Unser umfangreiches und hochwertiges Haushalts-Sortiment bietet jedem Innenaustatter hochwertige Produkte."
metaDescription = "Unser umfangreiches und hochwertiges Haushalts-Sortiment bietet jedem Innenaustatter hochwertige Produkte."

tags[] = "wohnen"
tags[] = "haus"
tags[] = "einrichtung"

tagsNot[] = "garten"
tagsNot[] = "pflanzen"
tagsNot[] = "haustiere"
tagsNot[] = "handschuhe"
tagsNot[] = "reinigungsmittel"

[3]

slug = "auto-zweirad"
name = "Auto & Zweiräder"
title = "Günstig Auto- und Zweiradzubehör online-shoppen vom Scheibenwischer bis zu Motorradhelmen"
description = "Unser umfangreiches und hochwertiges Auto- und Zweirad-Sortiment bietet jedem Fahrzeughalter hochwertige Produkte."
metaDescription = "Unser umfangreiches und hochwertiges Auto- und Zweirad-Sortiment bietet jedem Fahrzeughalter hochwertige Produkte."

tags[] = "auto"
tags[] = "fahrrad"
tags[] = "motorrad"

tagsNot[] = "garten"

[4]

slug = "elektro-licht"
name = "Elektro & Lampen"
title = "Günstig Elektronikartikel und Lampen shoppen vom Lampenschirm bis hin zum Rauchmelder."
description = "Unser umfangreiches und hochwertiges Elektronik- und Lampensortiment bietet eine große Auswahl an hochwertigen Produkten."
metaDescription = "Unser umfangreiches und hochwertiges Elektronik- und Lampensortiment bietet eine große Auswahl an hochwertigen Produkten."

tags[] = "elektronik"
tags[] = "lampen"
tags[] = "leuchtmittel"

tagsNot[] = "auto"
tagsNot[] = "zweirad"