[0]

slug = "tische"
name = "Tische"
title = "Günstig Tische Online-Shoppen von Esstischen bis hin zu Gartentischen"
description = "Unser umfangreiches und hochwertiges Tisch-Sortiment bietet jedem das passende Design fürs schöne und gemütliche zu Hause."
metaDescription = "Unser umfangreiches und hochwertiges Tisch-Sortiment bietet jedem das passende Design fürs schöne und gemütliche zu Hause."

tags[] = "tisch"
tags[] = "tische"

tagsNot[] = "spielzeug"

[1]

slug = "stuehle"
name = "Stühle"
title = "Günstig Stühle Online-Shoppen von passenden Stühlen zum Esstisch bis hin zu Gartenstühlen"
description = "Unser umfangreiches und hochwertiges Stuhl-Sortiment bietet jedem Tisch das passende Design fürs schöne zu Hause."
metaDescription = "Unser umfangreiches und hochwertiges Stuhl-Sortiment bietet jedem Tisch das passende Design fürs schöne zu Hause."

tags[] = "stuhl"
tags[] = "stuehle"

tagsNot[] = "spielzeug"

[2]

slug = "schlafen-betten"
name = "Schlafzimmer & Betten"
title = "Günstig Schlafzimmermöbel Online-Shoppen von passenden Betten bin hin zum Schlafzimmerschrank"
description = "Unser umfangreiches und hochwertiges Schlafzimmer-Sortiment bietet jedem das passende Bett für ein erholsame Nacht."
metaDescription = "Unser umfangreiches und hochwertiges Schlafzimmer-Sortiment bietet jedem das passende Bett für ein erholsame Nacht."

tags[] = "schlafzimmer"
tags[] = "bett"
tags[] = "betten"

tagsNot[] = "spielzeug"

[3]

slug = "sofas-sessel"
name = "Sofas & Sessel"
title = "Günstig Sofas & Sessel Online-Shoppen von der gemütlichen Couch bis zum eleganten Sofa"
description = "Unser umfangreiches und hochwertiges Wohnzimmer-Sortiment bietet jedem das passende Möbelstück für ein chices zu Hause."
metaDescription = "Unser umfangreiches und hochwertiges Wohnzimmer-Sortiment bietet jedem das passende Möbelstück für ein chices zu Hause."

tags[] = "sofa"
tags[] = "sofas"
tags[] = "couch"
tags[] = "sessel"

tagsNot[] = "spielzeug"

[4]

slug = "kueche-kochen"
name = "Küche & Accessoires"
title = "Günstig Küchen-Möbel und Küchen-Accessoires Online-Shoppen von der Gabel bis hin zum Esstisch"
description = "Unser umfangreiches und hochwertiges Schlafzimmer-Sortiment bietet jedem das passende Bett für ein erholsame Nacht."
metaDescription = "Unser umfangreiches und hochwertiges Schlafzimmer-Sortiment bietet jedem das passende Bett für ein erholsame Nacht."

tags[] = "kueche"
tags[] = "esstisch"

tagsNot[] = "spielzeug"

[5]

slug = "licht"
name = "Lampen & Licht"
title = "Günstig Lampen Online-Shoppen von edlen Standlampen bis hin zu dekorativen Außenlampen"
description = "Unser umfangreiches und hochwertiges Stuhl-Sortiment bietet jedem Tisch das passende Design fürs schöne zu Hause."
metaDescription = "Unser umfangreiches und hochwertiges Stuhl-Sortiment bietet jedem Tisch das passende Design fürs schöne zu Hause."

tags[] = "lampe"
tags[] = "lampen"

tagsNot[] = "spielzeug"

[6]

slug = "garten"
name = "Garten"
title = "Günstig Gartenmöbel Online-Shoppen von edlen Gartentischen bis hin zu dekorativen Außenleuchten"
description = "Unser umfangreiches und hochwertiges Garten-Sortiment bietet jedem Gärtner die passenden Gartenmöbel."
metaDescription = "Unser umfangreiches und hochwertiges Garten-Sortiment bietet jedem Gärtner die passenden Gartenmöbel."

tags[] = "garten"
tags[] = "terrasse"

tagsNot[] = "spielzeug"