[preset]

title = "Home & Living"

[home]

slug = "home"
name = "Home"
title = "Günstige Einrichtung, Möbel und Lampen für das Schöne zu Hause einkaufen"
description = "Stöbern Sie in unserem großen Sortiment von mehr als 100.000 Produkten von Lampen über Möbel bis hin zu edlen Küchenutensilien."
metaDescription = "Stöbern Sie in unserem großen Sortiment von mehr als 100.000 Produkten von Lampen über Möbel bis hin zu Küchenutensilien."